import re
from datetime import datetime



text = """Error 1776-10-11T18:13+12:00 eaque harum velit occaecati saepe. Tenetur occaecati corporis accusantium qui. Quae soluta nisi ad ullam ipsum. Sunt optio accusantium. Nulla eius consectetur. Libero est minus deleniti. Vero reprehenderit non cum reiciendis quos. Sapiente quo nobis amet ipsam nam occaecati. Exercitationem accusamus magnam inventore dolor. Soluta quidem esse voluptas esse debitis fugit eos. Quod veritatis et consectetur soluta ducimus vero. Ipsa tempora ullam ducimus sed corporis. In dolores perspiciatis modi omnis.
Aliquam reiciendis 1967-07-15 deserunt mollitia aspernatur quos maiores. Quis laborum corporis accusamus mollitia ratione non doloremque. Earum tenetur asperiores quisquam velit quo repellendus adipisci. Facere inventore deleniti nobis ea accusantium magnam. Quam quod tenetur a. Aperiam quae temporibus alias eaque. Rerum possimus corporis sapiente assumenda. Accusantium architecto consequatur sequi tempore similique quo earum. Ullam perspiciatis architecto ullam. Quae magni cupiditate. Dolor delectus unde totam libero. Nisi eos quas doloremque libero.
Voluptatibus aut eaque architecto. Deleniti dignissimos officiis eius rerum qui. Praesentium esse impedit laboriosam sed vel. Qui perspiciatis inventore. Libero incidunt aut suscipit 1107-13-26T19:55 modi. Consequuntur aspernatur odit aspernatur eveniet. Consequatur sunt eum officia minima iure repellendus. Quas explicabo facere amet eos nihil. Consequuntur modi sed deserunt exercitationem occaecati. Praesentium exercitationem expedita perferendis sunt neque. Cumque earum aliquam suscipit minima. Voluptatem laudantium earum atque. Doloremque nisi repellendus 
consequuntur autem. Atque beatae culpa dignissimos ullam. Hic natus accusantium quisquam provident pariatur. Exercitationem aperiam error ipsa optio animi. Molestias nisi dolores impedit quaerat a quod. Nulla beatae tenetur earum ad asperiores adipisci sapiente. Maiores laboriosam unde. Velit 1515-09-27T14:44 omnis aperiam 1800-11-05 aliquam.Eligendi aspernatur ex delectus unde. Qui voluptates aut nulla nam facere. Facere molestias dolore incidunt totam. Voluptas odio rem rem fugiat placeat. At doloremque harum ipsam laboriosam. In vitae architecto libero distinctio. 
Repudiandae provident veritatis 1853-12-24T09:13 consectetur. Iusto autem debitis fuga corrupti illum. Officiis quibusdam voluptate perspiciatis unde. Repellat velit architecto.Earum sapiente iure quam soluta. Beatae ea accusamus voluptas perspiciatis laboriosam. Corrupti veritatis dolor optio. Eum facere fuga a. Magni amet quam et praesentium. Facere commodi quaerat ullam. Quidem optio commodi odit nobis. Sunt laborum ducimus necessitatibus facilis 1753-13-10 exercitationem. Aut earum enim provident quam animi enim praesentium. Magnam necessitatibus quam voluptas dolorem facilis. Qui adipisci provident.
Quasi corporis dolor quos dolor nisi. A maiores nemo doloremque quas ad. Accusamus atque inventore. Enim magnam dolorem facere. Aliquam commodi ducimus laboriosam doloremque. Ducimus sed nesciunt dolorum earum quaerat recusandae. Cumque molestias cum repellat qui magnam. Neque facere iusto quod iure dolore pariatur. 1679-12-14 ab veniam animi rerum molestias assumenda. Non similique perspiciatis officiis voluptates architecto. Ipsa odit tenetur vitae excepturi sit enim ab. Aliquam cupiditate quisquam atque. Autem veniam magni.Ipsam ad consequuntur voluptatibus qui provident. Nam voluptatem soluta error placeat rerum. 
Nisi aliquam perferendis. Sapiente tempora facere qui cupiditate porro. Accusamus fuga quod quaerat nisi quidem. Hic nisi nulla aspernatur voluptatum 1696-11-02T16:05+23:00. Omnis enim suscipit eaque iure. Delectus delectus corporis sunt soluta. Fuga 1696-11-02T16:05+23:00 ad. Quidem laborum impedit.Pariatur eum accusantium nemo officia reiciendis. Sapiente hic ipsam voluptatibus. Provident dolorum consequatur odio voluptates neque. Alias laborum atque incidunt adipisci est 1996-02-05 natus. Autem minima totam vero assumenda deserunt. Mollitia 1576-02-14 totam. Vero accusantium dolorum amet nemo 1486-09-04. 
Id asperiores exercitationem.1988-12-23 1187-10-18 rerum dicta facere. Cupiditate possimus dolorum earum. Rerum dolor nostrum. 1768-01-31 earum sunt. Ab animi corrupti. Aperiam velit quae dolores sapiente. 1988-12-23 quasi et vel ipsa nisi aut. Commodi eaque sapiente quos. Qui eveniet quod. Repudiandae delectus officia facere placeat ullam impedit. Suscipit tenetur libero et.Excepturi dolores maiores suscipit. Animi distinctio aliquid. Assumenda consequuntur assumenda aspernatur quam aliquid. Illum praesentium nemo facilis. Tempore minima itaque id dignissimos pariatur. Atque aspernatur deleniti voluptatum 1169-09-26.
 Quod quas tenetur incidunt. Corporis facilis maxime quisquam nihil soluta. Modi delectus nostrum laborum dolorum. Recusandae quam tenetur eum dolore expedita non. Architecto ullam quod occaecati. Blanditiis qui minus adipisci. Exercitationem iste optio cum odit.Ex itaque debitis iste cumque. 1195-02-08 in neque eveniet. Illum possimus reiciendis sunt architecto iste. Commodi ipsum natus non consectetur doloremque quibusdam. Facilis aliquid quibusdam veritatis accusantium. Aperiam doloremque quibusdam beatae rem. Dolor accusantium consectetur libero.Tempora necessitatibus fugiat rem non. Rerum itaque pariatur saepe. 
 Excepturi exercitationem dolor eos quis reprehenderit. Num1883-10-22 provident facilis perferendis similique. 1289-01-14 nihil fugiat repellendus fugit 1883-10-22 praesentium. 1289-01-14 ipsum rerum accusamus sunt quas laboriosam. Dolorum rerum reprehenderit aperiam quo quae. In ullam itaque eligendi. Consectetur rerum in iste reiciendis facilis esse. Unde qui et quod ratione laborum.Consequuntur nam dignissimos adipisci unde saepe. Beatae blanditiis 2044-04-08T04:46 ratione. Itaque quos delectus similique repudiandae beatae eum. Reiciendis id illum aliquid.
 Totam asperiores nesciunt amet et. Fugiat nemo nesciunt nulla suscipit expedita nisi. Soluta dolorum consequuntur odio saepe culpa. Sit adipisci ipsum nemo sapiente modi. Exercitationem laboriosam voluptatem aliquam voluptatibus aperiam deleniti. Provident labore praesentium quidem animi porro provident. Molestias saepe blanditiis tempora.Ut ipsum officia architecto ea ad quod. Cum eius quidem voluptatum libero ab velit. Ratione temporibus fuga. Quidem veniam harum amet sequi omnis voluptatibus. Reiciendis occaecati adipisci libero sunt corporis. Optio rerum tenetur unde nesciunt culpa. 
 Fuga repudiandae ratione quaerat occaecati quasi ipsa. Consequatur itaque nam perferendis vitae sint fugit. Ipsam occaecati beatae reprehenderit. Illo sequi ad ipsa commodi praesentium facere. Provident quidem illum ex 1701-05-22T20:40+11:00 ducimus nostrum. Exercitationem exercitationem maxime esse commodi.Iste id omnis aliquid eaque odit illum. 1996-01-19 explicabo expedita vel doloremque consectetur. Voluptate ex excepturi nihil quam libero beatae. Aperiam 1527-04-17 possimus quam asperiores consequatur nisi mollitia. Facilis delectus libero. Laudantium nemo atque et. Quisquam laudantium occaecati. Dicta porro ut totam illum.
Soluta quis velit ducimus. Perspiciatis mollitia et voluptatum. 1110-10-21 harum maxime alias perferendis modi. Ratione expedita aut eius assumenda pariatur. Soluta labore pariatur facilis. Nisi nemo placeat sapiente architecto illo nostrum dolorum. 1587-10-30T12:01+11:00 doloremque corporis veniam saepe voluptatem.Pariatur voluptatem cum voluptates quibusdam. Placeat nam consequatur perferendis. Sequi a ea molestias ad molestias totam doloremque. Doloribus dignissimos delectus tempora voluptate eius nisi. Aliquam qui beatae nobis cum velit odio. Occaecati voluptas dolorem corrupti reiciendis. Quis ipsa a eum optio a. 1408-12-03T23:46 necessitatibus eaque ex totam.
 Voluptatibus 1080-07-24 temporibus cupiditate. Adipisci nihil fugiat dolor iure quae. Ducimus incidunt ducimus adipisci eaque dignissimos saepe adipisci. Sapiente inventore laborum. Autem at exercitationem asperiores mollitia quod debitis.Numquam error nulla similique veritatis quod. Debitis vitae necessitatibus enim ipsam labore. Ut nihil unde cum. Sapiente sunt non laborum assumenda error 1043-01-08T01:10. Possimus similique vitae fugit. 1809-01-09T02:40+08:00 autem odio maxime minima ex vitae iure. Cupiditate placeat consequuntur. Sed dignissimos provident quo amet cum expedita explicabo. Reprehenderit eius nihil esse fugit. Quisquam rem labore doloribus. Maxime ut sunt neque.
 Non perferendis excepturi quasi. Eligendi eaque a ratione. Repudiandae dolore laborum quaerat. Sint 2037-13-23T24:32+18:30 ex tenetur architecto nobis minima. Doloremque facilis saepe veniam. Sint 1106-06-14T19:13+05:30 ducimus quos repudiandae totam. Ipsum facilis deleniti veniam."""

regex = r"(\d{4})-(\d{2})-(\d{2})"

all_dates = re.findall(regex, text)

birthday = datetime.strptime('12/09/1995', '%d/%m/%Y').date()

dates = []

for date in all_dates:
    try:
        dates.append(datetime.strptime('-'.join(date), '%Y-%m-%d').date())
    except ValueError:
        continue

date = min(dates, key=lambda x: abs(x - birthday))

print(date.strftime("%d/%m/%Y"))

